### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by mkasprz** [ianwalter/file-record#6]
Hi.
I seriously would like to know how to use this extension. I tried searching for something in command pallet and didn't manage to find anything. I also looked at keybindings list with the same result.
Could You please explain how it should work? I know it's just an alpha, but as it's available in Marketplace I'd like to try it out.
At the end it's probably all about writing a nice "README.md". ;)
Thanks in advance!

**Comment by mkasprz** [comment]
Ok, I've found the `record` folder, but the files inside it seems empty. Is there any chance of getting some convenient explorer over the file changes?

**Comment by ianwalter** [comment]
Yea I haven't had much time to invest in this yet. Basically every time you save a file it saves a copy of the file in `.vscode/record` with the same relative path + the filename + .record extension / timestamp + the original file extension, e.g.:
`src/index.js` --> `.vscode/record/src/index.js.record/May 31, 2018, 3:57 PM.56.js`
That's all there is to it.

**Comment by mkasprz** [comment]
Ok, thank You, now I understand.
I believe I experience some bug though, because files got created, but they are empty. Furthermore, file names don't look like the one presented by You. That's an example of what I got: `2018 M06 1 00`. I believe it all could be connected with the fact that I use Windows and characters like `:` are not permitted as part of the file name there.

**Comment by ianwalter** [comment]
Ok I had a suspicion you were on Windows. Unfotunately my Windows PC is in the shop, but it should be an easy fix. I’ll see what I can do.

**Comment by ianwalter** [comment]
Ok, let me know if `v0.0.5` works for you.

**Comment by mkasprz** [comment]
Yes it does. Thank You for quick reaction!

**Comment by ianwalter** [comment]
Cool
