### ISSUE TITLE
What is this ? Can it work as a timelapse tool ? 

### ISSUE THREAD

**Issue by nukadelic** [ianwalter/file-record#99]
There is no information in the readme file, I was looking for some extension to show me the progress of the edited file from the moment it was created. Does it do that ? 

My objective was to record the whole process of my coding to show it as a gif or a web-based viewer file for youtube. There is an option in the editor to hold Ctrl+Z and revert to empty file, then keep pressing Ctrl+Y to show next step in my reasoning / live coding. Forgive my lack of time for not checking your source code and writing this question instead.

**Comment by ianwalter** [comment]
It saves a timestamped copy every time you hit save in `.vscode/record`. It was intended as a system to locally backup/restore file changes but I haven't had time to dedicate to it. I guess you could use this to do what you're describing, but I wouldn't know how to do that.
